/**
 * GENERATED by scripts/mintPins.ts from tests/fixtures/series-golden-corpus.json
 * + series-harness-baseline.json — do not hand-edit; edit the corpus and
 * regenerate. Minted 100 pins, 100 of them portable,
 * under 107 keys (some pins carry a baked-in-series alias).
 */
import type { ShelfPin } from './shelfPins'

/** By matched EDITION id — exact, and the only table before 2026-08-11. */
export const SHELF_PINS: Record<string, ShelfPin> = {
	"1797104802": {
		"series": "Holly Gibney",
		"position": "2",
		"source": "operator-stated"
	},
	"1800264011": {
		"series": "Ahriman",
		"position": "2",
		"source": "measured-hard"
	},
	"1800264259": {
		"series": "Ultramarines",
		"position": "1",
		"source": "current-correct-default"
	},
	"1800266413": {
		"series": "Dark Imperium",
		"position": "3",
		"source": "current-correct-default"
	},
	"1800266421": {
		"series": "Dark Imperium",
		"position": "1",
		"source": "operator-stated"
	},
	"B009XEKR3O": {
		"series": "Elantris",
		"position": "2",
		"source": "operator-stated"
	},
	"B00HFW9SUE": {
		"series": "The Legend of Drizzt",
		"position": "12",
		"displayTitle": "The Spine of the World",
		"source": "operator-stated"
	},
	"B00HNF85YI": {
		"series": "The Legend of Drizzt",
		"position": "13",
		"displayTitle": "Sea of Swords",
		"source": "operator-stated"
	},
	"B00IGB42TA": {
		"series": "The Legend of Drizzt",
		"position": "28",
		"source": "measured-hard"
	},
	"B00NFO6TY4": {
		"series": "The Legend of Drizzt",
		"position": "29",
		"source": "measured-hard"
	},
	"178999778X": {
		"series": "Ahriman",
		"position": "1",
		"source": "measured-hard"
	},
	"B0B4PMPLFD": {
		"series": "Ahriman",
		"position": "3",
		"source": "measured-hard"
	},
	"B085LMPX86": {
		"series": "Jack Ryan",
		"position": "30",
		"source": "operator-stated"
	},
	"B07B3DKWZZ": {
		"series": "Jack Ryan",
		"position": "25",
		"source": "operator-stated"
	},
	"B06XP2JSN1": {
		"series": "Jack Ryan",
		"position": "23",
		"source": "operator-stated"
	},
	"B00A9W1U58": {
		"series": "Jack Ryan",
		"position": "15",
		"source": "operator-stated"
	},
	"B081NWY9J5": {
		"series": "Jack Ryan",
		"position": "29",
		"source": "operator-stated"
	},
	"B07DK2KCJD": {
		"series": "Jack Ryan",
		"position": "26",
		"source": "operator-stated"
	},
	"B074HGCJZ8": {
		"series": "Jack Ryan",
		"position": "24",
		"source": "operator-stated"
	},
	"B08ZJXKFKW": {
		"series": "Jack Ryan",
		"position": "32",
		"source": "operator-stated"
	},
	"B0000DYXQT": {
		"series": "Jack Ryan",
		"position": "12",
		"source": "operator-stated"
	},
	"B004AY444A": {
		"series": "Jack Ryan",
		"position": "13",
		"source": "operator-stated"
	},
	"B006FX933G": {
		"series": "Jack Ryan",
		"position": "14",
		"source": "operator-stated"
	},
	"B00LACSZBI": {
		"series": "Jack Ryan",
		"position": "17",
		"source": "operator-stated"
	},
	"B00XV0XC6A": {
		"series": "Jack Ryan",
		"position": "19",
		"source": "operator-stated"
	},
	"B01CUP10FG": {
		"series": "Jack Ryan",
		"position": "21",
		"source": "operator-stated"
	},
	"B07N2YSTSN": {
		"series": "Jack Ryan",
		"position": "27",
		"source": "operator-stated"
	},
	"B004KAPD4Y": {
		"series": "Jack Ryan",
		"position": "2",
		"source": "operator-stated"
	},
	"B002V0KDY0": {
		"series": "Jack Ryan",
		"position": "11",
		"source": "operator-stated"
	},
	"B004FI1AZ2": {
		"series": "Jack Ryan",
		"position": "3",
		"source": "operator-stated"
	},
	"B004EBZ2GI": {
		"series": "Jack Ryan",
		"position": "4",
		"source": "operator-stated"
	},
	"B004XN6PVS": {
		"series": "Jack Ryan",
		"position": "5",
		"source": "operator-stated"
	},
	"B004JOAIDM": {
		"series": "Jack Ryan",
		"position": "7",
		"source": "operator-stated"
	},
	"B004ESTSSO": {
		"series": "Jack Ryan",
		"position": "8",
		"source": "operator-stated"
	},
	"B00PKJF5T2": {
		"series": "Jack Ryan",
		"position": "18",
		"source": "operator-stated"
	},
	"B011PVUJ4Y": {
		"series": "Jack Ryan",
		"position": "20",
		"source": "operator-stated"
	},
	"B01JKG9GQI": {
		"series": "Jack Ryan",
		"position": "22",
		"source": "operator-stated"
	},
	"B0BXNPQFH7": {
		"series": "Jack Ryan",
		"position": "28",
		"source": "operator-stated"
	},
	"B0BP876GP2": {
		"series": "Jack Ryan",
		"position": "37",
		"source": "operator-stated"
	},
	"B0CGRZ8QR5": {
		"series": "Jack Ryan",
		"position": "38",
		"source": "operator-stated"
	},
	"B004FHZQEO": {
		"series": "Jack Ryan",
		"position": "6",
		"source": "operator-stated"
	},
	"B004O3NH3G": {
		"series": "Jack Ryan",
		"position": "10",
		"source": "operator-stated"
	},
	"B0083WD9HS": {
		"series": "Hannibal Lecter",
		"position": "3",
		"source": "operator-stated"
	},
	"B004VLLJU4": {
		"series": "Hannibal Lecter",
		"position": "2",
		"source": "measured-hard"
	},
	"B00DZ0G088": {
		"series": "Riyria Chronicles",
		"position": "1",
		"source": "census-verdict"
	},
	"B00F5BVQQQ": {
		"series": "Riyria Chronicles",
		"position": "2",
		"source": "census-verdict"
	},
	"B0G6MTH7LC": {
		"series": "Riyria Chronicles",
		"position": "2.5",
		"source": "census-verdict"
	},
	"B0GDRVSG7Z": {
		"series": "Riyria Chronicles",
		"position": "2.6",
		"source": "census-verdict"
	},
	"B014WY3T34": {
		"series": "Riyria Chronicles",
		"position": "3",
		"source": "census-verdict"
	},
	"B0D7ZB7B7R": {
		"series": "Riyria Chronicles",
		"position": "5",
		"source": "census-verdict"
	},
	"B002UZKK2G": {
		"series": "The Original Shannara Trilogy",
		"position": "1",
		"source": "measured-hard"
	},
	"B002UZLC9G": {
		"series": "The Original Shannara Trilogy",
		"position": "2",
		"source": "measured-hard"
	},
	"B0716TZWX8": {
		"series": "The Original Shannara Trilogy",
		"position": "3",
		"source": "measured-hard"
	},
	"B0F4RTHZV5": {
		"series": "Secret Projects",
		"position": "5",
		"source": "census-verdict"
	},
	"B0DFMN335N": {
		"series": "Warhammer 40,000: Imperial Guard",
		"position": "1",
		"source": "census-verdict"
	},
	"B07B6FFH3H": {
		"series": "Percy Jackson and the Olympians",
		"position": "1",
		"source": "operator-stated"
	},
	"B000GB8WGM": {
		"series": "Percy Jackson and the Olympians",
		"position": "2",
		"source": "operator-stated"
	},
	"B000PSJBBG": {
		"series": "Percy Jackson and the Olympians",
		"position": "3",
		"source": "operator-stated"
	},
	"B001FVJHMK": {
		"series": "Percy Jackson and the Olympians",
		"position": "4",
		"source": "operator-stated"
	},
	"B0028TY17O": {
		"series": "Percy Jackson and the Olympians",
		"position": "5",
		"source": "operator-stated"
	},
	"B0CST52X6G": {
		"series": "Percy Jackson and the Olympians",
		"position": "7",
		"source": "operator-stated"
	},
	"B07LH5LMRX": {
		"series": "The Forerunner Saga",
		"position": "1",
		"source": "operator-stated"
	},
	"B00767AAFU": {
		"series": "The Forerunner Saga",
		"position": "2",
		"source": "operator-stated"
	},
	"B07LH72D8M": {
		"series": "The Forerunner Saga",
		"position": "3",
		"source": "operator-stated"
	},
	"B075QLD2C2": {
		"series": "Eisenhorn",
		"position": "1",
		"source": "operator-stated"
	},
	"B075QN2PZW": {
		"series": "Eisenhorn",
		"position": "2",
		"source": "operator-stated"
	},
	"B075QL2BHN": {
		"series": "Eisenhorn",
		"position": "3",
		"source": "operator-stated"
	},
	"B077PBVD8X": {
		"series": "Eisenhorn",
		"position": "0.2",
		"source": "operator-stated"
	},
	"B00J8VN0YU": {
		"series": "Bill Hodges",
		"position": "1",
		"source": "operator-stated"
	},
	"B00U7U0CJW": {
		"series": "Bill Hodges",
		"position": "2",
		"source": "operator-stated"
	},
	"B018RE0APU": {
		"series": "Bill Hodges",
		"position": "3",
		"source": "operator-stated"
	},
	"B0081TGOWK": {
		"series": "Diablo",
		"position": "8",
		"source": "operator-stated"
	},
	"B08J5JLLYN": {
		"series": "Diablo: The Sin War",
		"position": "2",
		"source": "measured-hard"
	},
	"B00HJCEGKM": {
		"series": "Unfettered",
		"position": "1",
		"source": "operator-stated"
	},
	"B07VYV6X1X": {
		"series": "The Horus Heresy: Primarchs",
		"position": "12",
		"source": "current-correct-default"
	},
	"B07D2JTQQS": {
		"series": "Jack Ryan",
		"position": "1",
		"source": "operator-stated"
	},
	"B09HKYYT9Q": {
		"series": "The Twice-dead King",
		"position": "1",
		"source": "current-correct-default"
	},
	"B00GM389IY": {
		"series": "Jack Ryan",
		"position": "16",
		"source": "operator-stated"
	},
	"B09PVN67Y6": {
		"series": "The Twice-dead King",
		"position": "2",
		"source": "current-correct-default"
	},
	"B09WZQQ5XC": {
		"series": "Forges of Mars",
		"position": "2",
		"source": "current-correct-default"
	},
	"B002UZMWNG": {
		"series": "Millennium",
		"position": "1",
		"source": "operator-stated"
	},
	"B0763ZZL1W": {
		"series": "The Horus Heresy: Primarchs",
		"position": "5",
		"source": "current-correct-default"
	},
	"180026643X": {
		"series": "Dark Imperium",
		"position": "2",
		"source": "current-correct-default"
	},
	"B077DGBRTY": {
		"series": "Blood Angels",
		"position": "3.5",
		"source": "current-correct-default"
	},
	"B00AXZZ23M": {
		"series": "The Legend of Drizzt",
		"position": "23",
		"displayTitle": "Gauntlgrym",
		"source": "measured-hard"
	},
	"B011879DJM": {
		"series": "The Legend of Drizzt",
		"position": "31",
		"displayTitle": "Archmage",
		"source": "measured-hard"
	},
	"B00AY0DEN6": {
		"series": "The Legend of Drizzt",
		"position": "24",
		"displayTitle": "Neverwinter",
		"source": "measured-hard"
	},
	"B09FC52TN9": {
		"series": "The Dresden Files",
		"position": "17.1",
		"source": "operator-stated"
	},
	"B075SM9TB7": {
		"series": "Space Marine Battles",
		"position": "2",
		"source": "operator-stated"
	},
	"B004I6ZR78": {
		"series": "Jack Ryan",
		"position": "9",
		"source": "operator-stated"
	},
	"B00J8LHN6Q": {
		"series": "Southern Reach",
		"position": "2",
		"source": "operator-stated"
	},
	"B00MX3Q2BS": {
		"series": "Southern Reach",
		"position": "3",
		"source": "operator-stated"
	},
	"B08WJL3YG2": {
		"series": "Dragon King Trilogy",
		"position": "1",
		"source": "operator-stated"
	},
	"B074CLGTFP": {
		"series": "Millennium",
		"position": "5",
		"source": "operator-stated"
	},
	"B0G5PPTS4V": {
		"series": "Farseer Trilogy",
		"position": "1",
		"source": "operator-stated"
	},
	"B003NYOBOQ": {
		"series": "Farseer Trilogy",
		"position": "2",
		"source": "operator-stated"
	},
	"B003XWVC0E": {
		"series": "Farseer Trilogy",
		"position": "3",
		"source": "operator-stated"
	},
	"B008Y4ZU3G": {
		"series": "Liveship Traders",
		"position": "1",
		"source": "operator-stated"
	},
	"B0040F3GN4": {
		"series": "Liveship Traders",
		"position": "3",
		"source": "operator-stated"
	},
	"B07BB3D7CR": {
		"series": "Rain Wild Chronicles",
		"position": "4",
		"source": "operator-stated"
	}
}

/**
 * The same pins by folded (title, author) — see pinKey. This is what lets one
 * table serve a library that matched the same book to a different edition; the
 * edition-id table above reaches 49 of 90 pins on the second server.
 */
export const SHELF_PINS_BY_KEY: Record<string, ShelfPin> = {
	"theemperorssoul|brandonsanderson": {
		"series": "Elantris",
		"position": "2",
		"source": "operator-stated"
	},
	"thespineoftheworldlegendofdrizztpathsofdarknessbook2|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "12",
		"displayTitle": "The Spine of the World",
		"source": "operator-stated"
	},
	"thespineoftheworld|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "12",
		"displayTitle": "The Spine of the World",
		"source": "operator-stated"
	},
	"seaofswordslegendofdrizztpathsofdarknessbook3|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "13",
		"displayTitle": "Sea of Swords",
		"source": "operator-stated"
	},
	"seaofswords|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "13",
		"displayTitle": "Sea of Swords",
		"source": "operator-stated"
	},
	"nightofthehunterlegendofdrizztcompanionscodexbooki|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "28",
		"source": "measured-hard"
	},
	"nightofthehunter|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "28",
		"source": "measured-hard"
	},
	"riseofthekinglegendofdrizztcompanionscodexbook2|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "29",
		"source": "measured-hard"
	},
	"riseoftheking|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "29",
		"source": "measured-hard"
	},
	"ahrimanexile|johnfrench": {
		"series": "Ahriman",
		"position": "1",
		"source": "measured-hard"
	},
	"ahrimansorcerer|johnfrench": {
		"series": "Ahriman",
		"position": "2",
		"source": "measured-hard"
	},
	"ahrimanunchanged|johnfrench": {
		"series": "Ahriman",
		"position": "3",
		"source": "measured-hard"
	},
	"tomclancyshadowofthedragon|marccameron": {
		"series": "Jack Ryan",
		"position": "30",
		"source": "operator-stated"
	},
	"tomclancylineofsight|mikemaden": {
		"series": "Jack Ryan",
		"position": "25",
		"source": "operator-stated"
	},
	"tomclancypointofcontact|mikemaden": {
		"series": "Jack Ryan",
		"position": "23",
		"source": "operator-stated"
	},
	"threatvector|markgreaney": {
		"series": "Jack Ryan",
		"position": "15",
		"source": "operator-stated"
	},
	"tomclancyfiringpoint|mikemaden": {
		"series": "Jack Ryan",
		"position": "29",
		"source": "operator-stated"
	},
	"tomclancyoathofoffice|marccameron": {
		"series": "Jack Ryan",
		"position": "26",
		"source": "operator-stated"
	},
	"tomclancypowerandempire|marccameron": {
		"series": "Jack Ryan",
		"position": "24",
		"source": "operator-stated"
	},
	"tomclancychainofcommand|marccameron": {
		"series": "Jack Ryan",
		"position": "32",
		"source": "operator-stated"
	},
	"theteethofthetiger|tomclancy": {
		"series": "Jack Ryan",
		"position": "12",
		"source": "operator-stated"
	},
	"deadoralive|tomclancy": {
		"series": "Jack Ryan",
		"position": "13",
		"source": "operator-stated"
	},
	"lockedon|tomclancy": {
		"series": "Jack Ryan",
		"position": "14",
		"source": "operator-stated"
	},
	"tomclancysupportanddefend|markgreaney": {
		"series": "Jack Ryan",
		"position": "17",
		"source": "operator-stated"
	},
	"tomclancyunderfire|grantblackwood": {
		"series": "Jack Ryan",
		"position": "19",
		"source": "operator-stated"
	},
	"tomclancydutyandhonor|grantblackwood": {
		"series": "Jack Ryan",
		"position": "21",
		"source": "operator-stated"
	},
	"tomclancyenemycontact|mikemaden": {
		"series": "Jack Ryan",
		"position": "27",
		"source": "operator-stated"
	},
	"patriotgames|tomclancy": {
		"series": "Jack Ryan",
		"position": "2",
		"source": "operator-stated"
	},
	"redrabbit|tomclancy": {
		"series": "Jack Ryan",
		"position": "11",
		"source": "operator-stated"
	},
	"thecardinalofthekremlin|tomclancy": {
		"series": "Jack Ryan",
		"position": "3",
		"source": "operator-stated"
	},
	"clearandpresentdanger|tomclancy": {
		"series": "Jack Ryan",
		"position": "4",
		"source": "operator-stated"
	},
	"thesumofallfears|tomclancy": {
		"series": "Jack Ryan",
		"position": "5",
		"source": "operator-stated"
	},
	"debtofhonor|tomclancy": {
		"series": "Jack Ryan",
		"position": "7",
		"source": "operator-stated"
	},
	"executiveorders|tomclancy": {
		"series": "Jack Ryan",
		"position": "8",
		"source": "operator-stated"
	},
	"fullforceandeffect|markgreaney": {
		"series": "Jack Ryan",
		"position": "18",
		"source": "operator-stated"
	},
	"tomclancycommanderinchief|markgreaney": {
		"series": "Jack Ryan",
		"position": "20",
		"source": "operator-stated"
	},
	"tomclancytruefaithandallegiance|markgreaney": {
		"series": "Jack Ryan",
		"position": "22",
		"source": "operator-stated"
	},
	"tomclancycodeofhonor|marccameron": {
		"series": "Jack Ryan",
		"position": "28",
		"source": "operator-stated"
	},
	"tomclancycommandandcontrol|marccameron": {
		"series": "Jack Ryan",
		"position": "37",
		"source": "operator-stated"
	},
	"tomclancyactofdefiance|brianandrews": {
		"series": "Jack Ryan",
		"position": "38",
		"source": "operator-stated"
	},
	"withoutremorse|tomclancy": {
		"series": "Jack Ryan",
		"position": "6",
		"source": "operator-stated"
	},
	"thebearandthedragon|tomclancy": {
		"series": "Jack Ryan",
		"position": "10",
		"source": "operator-stated"
	},
	"hannibal|thomasharris": {
		"series": "Hannibal Lecter",
		"position": "3",
		"source": "operator-stated"
	},
	"thesilenceofthelambs|thomasharris": {
		"series": "Hannibal Lecter",
		"position": "2",
		"source": "measured-hard"
	},
	"thecrowntower|michaeljsullivan": {
		"series": "Riyria Chronicles",
		"position": "1",
		"source": "census-verdict"
	},
	"theroseandthethorn|michaeljsullivan": {
		"series": "Riyria Chronicles",
		"position": "2",
		"source": "census-verdict"
	},
	"thejester|michaeljsullivan": {
		"series": "Riyria Chronicles",
		"position": "2.5",
		"source": "census-verdict"
	},
	"professionalintegrity|michaeljsullivan": {
		"series": "Riyria Chronicles",
		"position": "2.6",
		"source": "census-verdict"
	},
	"thedeathofdulgath|michaeljsullivan": {
		"series": "Riyria Chronicles",
		"position": "3",
		"source": "census-verdict"
	},
	"drumindor|michaeljsullivan": {
		"series": "Riyria Chronicles",
		"position": "5",
		"source": "census-verdict"
	},
	"theswordofshannara|terrybrooks": {
		"series": "The Original Shannara Trilogy",
		"position": "1",
		"source": "measured-hard"
	},
	"theelfstonesofshannara|terrybrooks": {
		"series": "The Original Shannara Trilogy",
		"position": "2",
		"source": "measured-hard"
	},
	"thewishsongofshannara|terrybrooks": {
		"series": "The Original Shannara Trilogy",
		"position": "3",
		"source": "measured-hard"
	},
	"islesoftheemberdark|brandonsanderson": {
		"series": "Secret Projects",
		"position": "5",
		"source": "census-verdict"
	},
	"baneblade|guyhaley": {
		"series": "Warhammer 40,000: Imperial Guard",
		"position": "1",
		"source": "census-verdict"
	},
	"thelightningthief|rickriordan": {
		"series": "Percy Jackson and the Olympians",
		"position": "1",
		"source": "operator-stated"
	},
	"theseaofmonsters|rickriordan": {
		"series": "Percy Jackson and the Olympians",
		"position": "2",
		"source": "operator-stated"
	},
	"thetitanscurse|rickriordan": {
		"series": "Percy Jackson and the Olympians",
		"position": "3",
		"source": "operator-stated"
	},
	"thebattleofthelabyrinth|rickriordan": {
		"series": "Percy Jackson and the Olympians",
		"position": "4",
		"source": "operator-stated"
	},
	"thelastolympian|rickriordan": {
		"series": "Percy Jackson and the Olympians",
		"position": "5",
		"source": "operator-stated"
	},
	"percyjacksonandtheolympianswrathofthetriplegoddess|rickriordan": {
		"series": "Percy Jackson and the Olympians",
		"position": "7",
		"source": "operator-stated"
	},
	"halocryptum|gregbear": {
		"series": "The Forerunner Saga",
		"position": "1",
		"source": "operator-stated"
	},
	"haloprimordium|gregbear": {
		"series": "The Forerunner Saga",
		"position": "2",
		"source": "operator-stated"
	},
	"halosilentium|gregbear": {
		"series": "The Forerunner Saga",
		"position": "3",
		"source": "operator-stated"
	},
	"xenos|danabnett": {
		"series": "Eisenhorn",
		"position": "1",
		"source": "operator-stated"
	},
	"malleus|danabnett": {
		"series": "Eisenhorn",
		"position": "2",
		"source": "operator-stated"
	},
	"hereticus|danabnett": {
		"series": "Eisenhorn",
		"position": "3",
		"source": "operator-stated"
	},
	"masterimusstransgression|danabnett": {
		"series": "Eisenhorn",
		"position": "0.2",
		"source": "operator-stated"
	},
	"mrmercedes|stephenking": {
		"series": "Bill Hodges",
		"position": "1",
		"source": "operator-stated"
	},
	"finderskeepers|stephenking": {
		"series": "Bill Hodges",
		"position": "2",
		"source": "operator-stated"
	},
	"endofwatch|stephenking": {
		"series": "Bill Hodges",
		"position": "3",
		"source": "operator-stated"
	},
	"ifitbleeds|stephenking": {
		"series": "Holly Gibney",
		"position": "2",
		"source": "operator-stated"
	},
	"diabloiiitheorder|natekenyon": {
		"series": "Diablo",
		"position": "8",
		"source": "operator-stated"
	},
	"diablothesinwarbooktwo|richardaknaak": {
		"series": "Diablo: The Sin War",
		"position": "2",
		"source": "measured-hard"
	},
	"unfettered|terrybrooks": {
		"series": "Unfettered",
		"position": "1",
		"source": "operator-stated"
	},
	"konradcurzethenighthaunter|guyhaley": {
		"series": "The Horus Heresy: Primarchs",
		"position": "12",
		"source": "current-correct-default"
	},
	"thehuntforredoctober|tomclancy": {
		"series": "Jack Ryan",
		"position": "1",
		"source": "operator-stated"
	},
	"thetwicedeadkingruin|natecrowley": {
		"series": "The Twice-dead King",
		"position": "1",
		"source": "current-correct-default"
	},
	"nightbringer|grahammcneill": {
		"series": "Ultramarines",
		"position": "1",
		"source": "current-correct-default"
	},
	"godblight|guyhaley": {
		"series": "Dark Imperium",
		"position": "3",
		"source": "current-correct-default"
	},
	"commandauthority|tomclancy": {
		"series": "Jack Ryan",
		"position": "16",
		"source": "operator-stated"
	},
	"thetwicedeadkingreign|natecrowley": {
		"series": "The Twice-dead King",
		"position": "2",
		"source": "current-correct-default"
	},
	"lordsofmars|grahammcneill": {
		"series": "Forges of Mars",
		"position": "2",
		"source": "current-correct-default"
	},
	"thegirlwiththedragontattoo|stieglarsson": {
		"series": "Millennium",
		"position": "1",
		"source": "operator-stated"
	},
	"lorgarbeareroftheword|gavthorpe": {
		"series": "The Horus Heresy: Primarchs",
		"position": "5",
		"source": "current-correct-default"
	},
	"plaguewar|guyhaley": {
		"series": "Dark Imperium",
		"position": "2",
		"source": "current-correct-default"
	},
	"heartofrage|jamesswallow": {
		"series": "Blood Angels",
		"position": "3.5",
		"source": "current-correct-default"
	},
	"gauntlgrymlegendofdrizzt|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "23",
		"displayTitle": "Gauntlgrym",
		"source": "measured-hard"
	},
	"gauntlgrym|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "23",
		"displayTitle": "Gauntlgrym",
		"source": "measured-hard"
	},
	"archmagelegendofdrizzt|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "31",
		"displayTitle": "Archmage",
		"source": "measured-hard"
	},
	"archmage|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "31",
		"displayTitle": "Archmage",
		"source": "measured-hard"
	},
	"neverwinterlegendofdrizzt|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "24",
		"displayTitle": "Neverwinter",
		"source": "measured-hard"
	},
	"neverwinter|rasalvatore": {
		"series": "The Legend of Drizzt",
		"position": "24",
		"displayTitle": "Neverwinter",
		"source": "measured-hard"
	},
	"heroichearts|jimbutcher": {
		"series": "The Dresden Files",
		"position": "17.1",
		"source": "operator-stated"
	},
	"darkimperium|guyhaley": {
		"series": "Dark Imperium",
		"position": "1",
		"source": "operator-stated"
	},
	"helsreach|aarondembskibowden": {
		"series": "Space Marine Battles",
		"position": "2",
		"source": "operator-stated"
	},
	"rainbowsix|tomclancy": {
		"series": "Jack Ryan",
		"position": "9",
		"source": "operator-stated"
	},
	"authority|jeffvandermeer": {
		"series": "Southern Reach",
		"position": "2",
		"source": "operator-stated"
	},
	"acceptance|jeffvandermeer": {
		"series": "Southern Reach",
		"position": "3",
		"source": "operator-stated"
	},
	"inthehallofthedragonking|stephenrlawhead": {
		"series": "Dragon King Trilogy",
		"position": "1",
		"source": "operator-stated"
	},
	"thegirlwhotakesaneyeforaneye|davidlagercrantz": {
		"series": "Millennium",
		"position": "5",
		"source": "operator-stated"
	},
	"assassinsapprentice|robinhobb": {
		"series": "Farseer Trilogy",
		"position": "1",
		"source": "operator-stated"
	},
	"royalassassin|robinhobb": {
		"series": "Farseer Trilogy",
		"position": "2",
		"source": "operator-stated"
	},
	"assassinsquest|robinhobb": {
		"series": "Farseer Trilogy",
		"position": "3",
		"source": "operator-stated"
	},
	"shipofmagic|robinhobb": {
		"series": "Liveship Traders",
		"position": "1",
		"source": "operator-stated"
	},
	"shipofdestiny|robinhobb": {
		"series": "Liveship Traders",
		"position": "3",
		"source": "operator-stated"
	},
	"bloodofdragons|robinhobb": {
		"series": "Rain Wild Chronicles",
		"position": "4",
		"source": "operator-stated"
	}
}

/**
 * recordId -> EVERY portable key minted for it. Only the liveness gate needs this:
 * it is how "this pin is dead by id but alive by key" is decided EXACTLY rather
 * than by matching on the answer two different pins could share.
 */
export const SHELF_PIN_KEYS: Record<string, string[]> = {
	"1797104802": [
		"ifitbleeds|stephenking"
	],
	"1800264011": [
		"ahrimansorcerer|johnfrench"
	],
	"1800264259": [
		"nightbringer|grahammcneill"
	],
	"1800266413": [
		"godblight|guyhaley"
	],
	"1800266421": [
		"darkimperium|guyhaley"
	],
	"B009XEKR3O": [
		"theemperorssoul|brandonsanderson"
	],
	"B00HFW9SUE": [
		"thespineoftheworldlegendofdrizztpathsofdarknessbook2|rasalvatore",
		"thespineoftheworld|rasalvatore"
	],
	"B00HNF85YI": [
		"seaofswordslegendofdrizztpathsofdarknessbook3|rasalvatore",
		"seaofswords|rasalvatore"
	],
	"B00IGB42TA": [
		"nightofthehunterlegendofdrizztcompanionscodexbooki|rasalvatore",
		"nightofthehunter|rasalvatore"
	],
	"B00NFO6TY4": [
		"riseofthekinglegendofdrizztcompanionscodexbook2|rasalvatore",
		"riseoftheking|rasalvatore"
	],
	"178999778X": [
		"ahrimanexile|johnfrench"
	],
	"B0B4PMPLFD": [
		"ahrimanunchanged|johnfrench"
	],
	"B085LMPX86": [
		"tomclancyshadowofthedragon|marccameron"
	],
	"B07B3DKWZZ": [
		"tomclancylineofsight|mikemaden"
	],
	"B06XP2JSN1": [
		"tomclancypointofcontact|mikemaden"
	],
	"B00A9W1U58": [
		"threatvector|markgreaney"
	],
	"B081NWY9J5": [
		"tomclancyfiringpoint|mikemaden"
	],
	"B07DK2KCJD": [
		"tomclancyoathofoffice|marccameron"
	],
	"B074HGCJZ8": [
		"tomclancypowerandempire|marccameron"
	],
	"B08ZJXKFKW": [
		"tomclancychainofcommand|marccameron"
	],
	"B0000DYXQT": [
		"theteethofthetiger|tomclancy"
	],
	"B004AY444A": [
		"deadoralive|tomclancy"
	],
	"B006FX933G": [
		"lockedon|tomclancy"
	],
	"B00LACSZBI": [
		"tomclancysupportanddefend|markgreaney"
	],
	"B00XV0XC6A": [
		"tomclancyunderfire|grantblackwood"
	],
	"B01CUP10FG": [
		"tomclancydutyandhonor|grantblackwood"
	],
	"B07N2YSTSN": [
		"tomclancyenemycontact|mikemaden"
	],
	"B004KAPD4Y": [
		"patriotgames|tomclancy"
	],
	"B002V0KDY0": [
		"redrabbit|tomclancy"
	],
	"B004FI1AZ2": [
		"thecardinalofthekremlin|tomclancy"
	],
	"B004EBZ2GI": [
		"clearandpresentdanger|tomclancy"
	],
	"B004XN6PVS": [
		"thesumofallfears|tomclancy"
	],
	"B004JOAIDM": [
		"debtofhonor|tomclancy"
	],
	"B004ESTSSO": [
		"executiveorders|tomclancy"
	],
	"B00PKJF5T2": [
		"fullforceandeffect|markgreaney"
	],
	"B011PVUJ4Y": [
		"tomclancycommanderinchief|markgreaney"
	],
	"B01JKG9GQI": [
		"tomclancytruefaithandallegiance|markgreaney"
	],
	"B0BXNPQFH7": [
		"tomclancycodeofhonor|marccameron"
	],
	"B0BP876GP2": [
		"tomclancycommandandcontrol|marccameron"
	],
	"B0CGRZ8QR5": [
		"tomclancyactofdefiance|brianandrews"
	],
	"B004FHZQEO": [
		"withoutremorse|tomclancy"
	],
	"B004O3NH3G": [
		"thebearandthedragon|tomclancy"
	],
	"B0083WD9HS": [
		"hannibal|thomasharris"
	],
	"B004VLLJU4": [
		"thesilenceofthelambs|thomasharris"
	],
	"B00DZ0G088": [
		"thecrowntower|michaeljsullivan"
	],
	"B00F5BVQQQ": [
		"theroseandthethorn|michaeljsullivan"
	],
	"B0G6MTH7LC": [
		"thejester|michaeljsullivan"
	],
	"B0GDRVSG7Z": [
		"professionalintegrity|michaeljsullivan"
	],
	"B014WY3T34": [
		"thedeathofdulgath|michaeljsullivan"
	],
	"B0D7ZB7B7R": [
		"drumindor|michaeljsullivan"
	],
	"B002UZKK2G": [
		"theswordofshannara|terrybrooks"
	],
	"B002UZLC9G": [
		"theelfstonesofshannara|terrybrooks"
	],
	"B0716TZWX8": [
		"thewishsongofshannara|terrybrooks"
	],
	"B0F4RTHZV5": [
		"islesoftheemberdark|brandonsanderson"
	],
	"B0DFMN335N": [
		"baneblade|guyhaley"
	],
	"B07B6FFH3H": [
		"thelightningthief|rickriordan"
	],
	"B000GB8WGM": [
		"theseaofmonsters|rickriordan"
	],
	"B000PSJBBG": [
		"thetitanscurse|rickriordan"
	],
	"B001FVJHMK": [
		"thebattleofthelabyrinth|rickriordan"
	],
	"B0028TY17O": [
		"thelastolympian|rickriordan"
	],
	"B0CST52X6G": [
		"percyjacksonandtheolympianswrathofthetriplegoddess|rickriordan"
	],
	"B07LH5LMRX": [
		"halocryptum|gregbear"
	],
	"B00767AAFU": [
		"haloprimordium|gregbear"
	],
	"B07LH72D8M": [
		"halosilentium|gregbear"
	],
	"B075QLD2C2": [
		"xenos|danabnett"
	],
	"B075QN2PZW": [
		"malleus|danabnett"
	],
	"B075QL2BHN": [
		"hereticus|danabnett"
	],
	"B077PBVD8X": [
		"masterimusstransgression|danabnett"
	],
	"B00J8VN0YU": [
		"mrmercedes|stephenking"
	],
	"B00U7U0CJW": [
		"finderskeepers|stephenking"
	],
	"B018RE0APU": [
		"endofwatch|stephenking"
	],
	"B0081TGOWK": [
		"diabloiiitheorder|natekenyon"
	],
	"B08J5JLLYN": [
		"diablothesinwarbooktwo|richardaknaak"
	],
	"B00HJCEGKM": [
		"unfettered|terrybrooks"
	],
	"B07VYV6X1X": [
		"konradcurzethenighthaunter|guyhaley"
	],
	"B07D2JTQQS": [
		"thehuntforredoctober|tomclancy"
	],
	"B09HKYYT9Q": [
		"thetwicedeadkingruin|natecrowley"
	],
	"B00GM389IY": [
		"commandauthority|tomclancy"
	],
	"B09PVN67Y6": [
		"thetwicedeadkingreign|natecrowley"
	],
	"B09WZQQ5XC": [
		"lordsofmars|grahammcneill"
	],
	"B002UZMWNG": [
		"thegirlwiththedragontattoo|stieglarsson"
	],
	"B0763ZZL1W": [
		"lorgarbeareroftheword|gavthorpe"
	],
	"180026643X": [
		"plaguewar|guyhaley"
	],
	"B077DGBRTY": [
		"heartofrage|jamesswallow"
	],
	"B00AXZZ23M": [
		"gauntlgrymlegendofdrizzt|rasalvatore",
		"gauntlgrym|rasalvatore"
	],
	"B011879DJM": [
		"archmagelegendofdrizzt|rasalvatore",
		"archmage|rasalvatore"
	],
	"B00AY0DEN6": [
		"neverwinterlegendofdrizzt|rasalvatore",
		"neverwinter|rasalvatore"
	],
	"B09FC52TN9": [
		"heroichearts|jimbutcher"
	],
	"B075SM9TB7": [
		"helsreach|aarondembskibowden"
	],
	"B004I6ZR78": [
		"rainbowsix|tomclancy"
	],
	"B00J8LHN6Q": [
		"authority|jeffvandermeer"
	],
	"B00MX3Q2BS": [
		"acceptance|jeffvandermeer"
	],
	"B08WJL3YG2": [
		"inthehallofthedragonking|stephenrlawhead"
	],
	"B074CLGTFP": [
		"thegirlwhotakesaneyeforaneye|davidlagercrantz"
	],
	"B0G5PPTS4V": [
		"assassinsapprentice|robinhobb"
	],
	"B003NYOBOQ": [
		"royalassassin|robinhobb"
	],
	"B003XWVC0E": [
		"assassinsquest|robinhobb"
	],
	"B008Y4ZU3G": [
		"shipofmagic|robinhobb"
	],
	"B0040F3GN4": [
		"shipofdestiny|robinhobb"
	],
	"B07BB3D7CR": [
		"bloodofdragons|robinhobb"
	]
}
