/**
 * GENERATED by scripts/mintPins.ts from tests/fixtures/series-golden-corpus.json
 * + series-harness-baseline.json — do not hand-edit; edit the corpus and
 * regenerate. Minted 90 pins.
 */
import type { ShelfPin } from './shelfPins'

export const SHELF_PINS: Record<string, ShelfPin> = {
	'1797104802': {
		series: 'Holly Gibney',
		position: '2',
		source: 'operator-stated'
	},
	'1800264011': {
		series: 'Ahriman',
		position: '2',
		source: 'measured-hard'
	},
	'1800264259': {
		series: 'Ultramarines',
		position: '1',
		source: 'current-correct-default'
	},
	'1800266413': {
		series: 'Dark Imperium',
		position: '3',
		source: 'current-correct-default'
	},
	'1800266421': {
		series: 'Dark Imperium',
		position: '1',
		source: 'operator-stated'
	},
	B00HFW9SUE: {
		series: 'The Legend of Drizzt',
		position: '12',
		displayTitle: 'The Spine of the World',
		source: 'operator-stated'
	},
	B00HNF85YI: {
		series: 'The Legend of Drizzt',
		position: '13',
		displayTitle: 'Sea of Swords',
		source: 'operator-stated'
	},
	B00IGB42TA: {
		series: 'The Legend of Drizzt',
		position: '28',
		source: 'measured-hard'
	},
	B00NFO6TY4: {
		series: 'The Legend of Drizzt',
		position: '29',
		source: 'measured-hard'
	},
	'178999778X': {
		series: 'Ahriman',
		position: '1',
		source: 'measured-hard'
	},
	B0B4PMPLFD: {
		series: 'Ahriman',
		position: '3',
		source: 'measured-hard'
	},
	B085LMPX86: {
		series: 'Jack Ryan',
		position: '30',
		source: 'operator-stated'
	},
	B07B3DKWZZ: {
		series: 'Jack Ryan',
		position: '25',
		source: 'operator-stated'
	},
	B06XP2JSN1: {
		series: 'Jack Ryan',
		position: '23',
		source: 'operator-stated'
	},
	B00A9W1U58: {
		series: 'Jack Ryan',
		position: '15',
		source: 'operator-stated'
	},
	B081NWY9J5: {
		series: 'Jack Ryan',
		position: '29',
		source: 'operator-stated'
	},
	B07DK2KCJD: {
		series: 'Jack Ryan',
		position: '26',
		source: 'operator-stated'
	},
	B074HGCJZ8: {
		series: 'Jack Ryan',
		position: '24',
		source: 'operator-stated'
	},
	B08ZJXKFKW: {
		series: 'Jack Ryan',
		position: '32',
		source: 'operator-stated'
	},
	B0000DYXQT: {
		series: 'Jack Ryan',
		position: '12',
		source: 'operator-stated'
	},
	B004AY444A: {
		series: 'Jack Ryan',
		position: '13',
		source: 'operator-stated'
	},
	B006FX933G: {
		series: 'Jack Ryan',
		position: '14',
		source: 'operator-stated'
	},
	B00LACSZBI: {
		series: 'Jack Ryan',
		position: '17',
		source: 'operator-stated'
	},
	B00XV0XC6A: {
		series: 'Jack Ryan',
		position: '19',
		source: 'operator-stated'
	},
	B01CUP10FG: {
		series: 'Jack Ryan',
		position: '21',
		source: 'operator-stated'
	},
	B07N2YSTSN: {
		series: 'Jack Ryan',
		position: '27',
		source: 'operator-stated'
	},
	B004KAPD4Y: {
		series: 'Jack Ryan',
		position: '2',
		source: 'operator-stated'
	},
	B002V0KDY0: {
		series: 'Jack Ryan',
		position: '11',
		source: 'operator-stated'
	},
	B004FI1AZ2: {
		series: 'Jack Ryan',
		position: '3',
		source: 'operator-stated'
	},
	B004EBZ2GI: {
		series: 'Jack Ryan',
		position: '4',
		source: 'operator-stated'
	},
	B004XN6PVS: {
		series: 'Jack Ryan',
		position: '5',
		source: 'operator-stated'
	},
	B004JOAIDM: {
		series: 'Jack Ryan',
		position: '7',
		source: 'operator-stated'
	},
	B004ESTSSO: {
		series: 'Jack Ryan',
		position: '8',
		source: 'operator-stated'
	},
	B00PKJF5T2: {
		series: 'Jack Ryan',
		position: '18',
		source: 'operator-stated'
	},
	B011PVUJ4Y: {
		series: 'Jack Ryan',
		position: '20',
		source: 'operator-stated'
	},
	B01JKG9GQI: {
		series: 'Jack Ryan',
		position: '22',
		source: 'operator-stated'
	},
	B0BXNPQFH7: {
		series: 'Jack Ryan',
		position: '28',
		source: 'operator-stated'
	},
	B0BP876GP2: {
		series: 'Jack Ryan',
		position: '37',
		source: 'operator-stated'
	},
	B0CGRZ8QR5: {
		series: 'Jack Ryan',
		position: '38',
		source: 'operator-stated'
	},
	B004FHZQEO: {
		series: 'Jack Ryan',
		position: '6',
		source: 'operator-stated'
	},
	B004O3NH3G: {
		series: 'Jack Ryan',
		position: '10',
		source: 'operator-stated'
	},
	B0083WD9HS: {
		series: 'Hannibal Lecter',
		position: '3',
		source: 'operator-stated'
	},
	B004VLLJU4: {
		series: 'Hannibal Lecter',
		position: '2',
		source: 'measured-hard'
	},
	B00DZ0G088: {
		series: 'The Riyria Chronicles',
		position: '1',
		source: 'census-verdict'
	},
	B00F5BVQQQ: {
		series: 'The Riyria Chronicles',
		position: '2',
		source: 'census-verdict'
	},
	B0G6MTH7LC: {
		series: 'The Riyria Chronicles',
		position: '2.5',
		source: 'census-verdict'
	},
	B0GDRVSG7Z: {
		series: 'The Riyria Chronicles',
		position: '2.6',
		source: 'census-verdict'
	},
	B014WY3T34: {
		series: 'The Riyria Chronicles',
		position: '3',
		source: 'census-verdict'
	},
	B0D7ZB7B7R: {
		series: 'The Riyria Chronicles',
		position: '5',
		source: 'census-verdict'
	},
	B002UZKK2G: {
		series: 'The Original Shannara Trilogy',
		position: '1',
		source: 'measured-hard'
	},
	B002UZLC9G: {
		series: 'The Original Shannara Trilogy',
		position: '2',
		source: 'measured-hard'
	},
	B0716TZWX8: {
		series: 'The Original Shannara Trilogy',
		position: '3',
		source: 'measured-hard'
	},
	B0DFMN335N: {
		series: 'Warhammer 40,000: Imperial Guard',
		position: '1',
		source: 'census-verdict'
	},
	B07B6FFH3H: {
		series: 'Percy Jackson and the Olympians',
		position: '1',
		source: 'operator-stated'
	},
	B000GB8WGM: {
		series: 'Percy Jackson and the Olympians',
		position: '2',
		source: 'operator-stated'
	},
	B000PSJBBG: {
		series: 'Percy Jackson and the Olympians',
		position: '3',
		source: 'operator-stated'
	},
	B001FVJHMK: {
		series: 'Percy Jackson and the Olympians',
		position: '4',
		source: 'operator-stated'
	},
	B0028TY17O: {
		series: 'Percy Jackson and the Olympians',
		position: '5',
		source: 'operator-stated'
	},
	B0CST52X6G: {
		series: 'Percy Jackson and the Olympians',
		position: '7',
		source: 'operator-stated'
	},
	B07LH5LMRX: {
		series: 'The Forerunner Saga',
		position: '1',
		source: 'operator-stated'
	},
	B00767AAFU: {
		series: 'The Forerunner Saga',
		position: '2',
		source: 'operator-stated'
	},
	B07LH72D8M: {
		series: 'The Forerunner Saga',
		position: '3',
		source: 'operator-stated'
	},
	B075QLD2C2: {
		series: 'Eisenhorn',
		position: '1',
		source: 'operator-stated'
	},
	B075QN2PZW: {
		series: 'Eisenhorn',
		position: '2',
		source: 'operator-stated'
	},
	B075QL2BHN: {
		series: 'Eisenhorn',
		position: '3',
		source: 'operator-stated'
	},
	B077PBVD8X: {
		series: 'Eisenhorn',
		position: '0.2',
		source: 'operator-stated'
	},
	B00J8VN0YU: {
		series: 'Bill Hodges',
		position: '1',
		source: 'operator-stated'
	},
	B00U7U0CJW: {
		series: 'Bill Hodges',
		position: '2',
		source: 'operator-stated'
	},
	B018RE0APU: {
		series: 'Bill Hodges',
		position: '3',
		source: 'operator-stated'
	},
	B0081TGOWK: {
		series: 'Diablo',
		position: '8',
		source: 'operator-stated'
	},
	B08J5JLLYN: {
		series: 'Diablo: The Sin War',
		position: '2',
		source: 'measured-hard'
	},
	B00HJCEGKM: {
		series: 'Unfettered',
		position: '1',
		source: 'operator-stated'
	},
	B07VYV6X1X: {
		series: 'The Horus Heresy: Primarchs',
		position: '12',
		source: 'current-correct-default'
	},
	B07D2JTQQS: {
		series: 'Jack Ryan',
		position: '1',
		source: 'operator-stated'
	},
	B09HKYYT9Q: {
		series: 'The Twice-dead King',
		position: '1',
		source: 'current-correct-default'
	},
	B00GM389IY: {
		series: 'Jack Ryan',
		position: '16',
		source: 'operator-stated'
	},
	B09PVN67Y6: {
		series: 'The Twice-dead King',
		position: '2',
		source: 'current-correct-default'
	},
	B09WZQQ5XC: {
		series: 'Forges of Mars',
		position: '2',
		source: 'current-correct-default'
	},
	B0763ZZL1W: {
		series: 'The Horus Heresy: Primarchs',
		position: '5',
		source: 'current-correct-default'
	},
	'180026643X': {
		series: 'Dark Imperium',
		position: '2',
		source: 'current-correct-default'
	},
	B077DGBRTY: {
		series: 'Blood Angels',
		position: '3.5',
		source: 'current-correct-default'
	},
	B00AXZZ23M: {
		series: 'The Legend of Drizzt',
		position: '23',
		displayTitle: 'Gauntlgrym',
		source: 'measured-hard'
	},
	B011879DJM: {
		series: 'The Legend of Drizzt',
		position: '31',
		displayTitle: 'Archmage',
		source: 'measured-hard'
	},
	B00AY0DEN6: {
		series: 'The Legend of Drizzt',
		position: '24',
		displayTitle: 'Neverwinter',
		source: 'measured-hard'
	},
	B09FC52TN9: {
		series: 'The Dresden Files',
		position: '17.1',
		source: 'operator-stated'
	},
	B075SM9TB7: {
		series: 'Space Marine Battles',
		position: '2',
		source: 'operator-stated'
	},
	B004I6ZR78: {
		series: 'Jack Ryan',
		position: '9',
		source: 'operator-stated'
	},
	B00J8LHN6Q: {
		series: 'Southern Reach',
		position: '2',
		source: 'operator-stated'
	},
	B00MX3Q2BS: {
		series: 'Southern Reach',
		position: '3',
		source: 'operator-stated'
	},
	B08WJL3YG2: {
		series: 'The Dragon King Trilogy',
		position: '1',
		source: 'operator-stated'
	}
}
