/**
 * GENERATED by scripts/mintPins.ts from tests/fixtures/series-golden-corpus.json
 * + series-harness-baseline.json — do not hand-edit; edit the corpus and
 * regenerate. Minted 44 pins.
 */
import type { ShelfPin } from './shelfPins'

export const SHELF_PINS: Record<string, ShelfPin> = {
	'1789994462': {
		series: 'The Horus Heresy: Primarchs',
		position: '12',
		source: 'current-correct-default'
	},
	'1800264011': {
		series: 'Ahriman',
		position: '2',
		source: 'measured-hard'
	},
	'1800264259': {
		series: 'Ultramarines',
		position: '1',
		source: 'current-correct-default'
	},
	'1800266413': {
		series: 'Dark Imperium',
		position: '3',
		source: 'current-correct-default'
	},
	'1800266421': {
		series: 'Dark Imperium',
		position: '1',
		source: 'operator-stated'
	},
	'1950366294': {
		series: 'Diablo: The Sin War',
		position: '2',
		source: 'measured-hard'
	},
	B00HFW9SUE: {
		series: 'The Legend of Drizzt',
		position: '12',
		displayTitle: 'The Spine of the World',
		source: 'operator-stated'
	},
	B00HNF85YI: {
		series: 'The Legend of Drizzt',
		position: '13',
		displayTitle: 'Sea of Swords',
		source: 'operator-stated'
	},
	'apple-audiobook-824435136': {
		series: 'The Legend of Drizzt',
		position: '28',
		source: 'measured-hard'
	},
	'apple-audiobook-923599546': {
		series: 'The Legend of Drizzt',
		position: '29',
		source: 'measured-hard'
	},
	'178999778X': {
		series: 'Ahriman',
		position: '1',
		source: 'measured-hard'
	},
	B0B4PMPLFD: {
		series: 'Ahriman',
		position: '3',
		source: 'measured-hard'
	},
	'0593287371': {
		series: 'Jack Ryan',
		position: '17',
		source: 'operator-stated'
	},
	B07B3QDGFS: {
		series: 'Jack Ryan, Jr.',
		position: '11',
		source: 'operator-stated'
	},
	B06XP12NZC: {
		series: 'Jack Ryan, Jr.',
		position: '10',
		source: 'operator-stated'
	},
	B00A9W1U58: {
		series: 'Jack Ryan, Jr.',
		position: '4',
		source: 'measured-hard'
	},
	'0593216229': {
		series: 'Jack Ryan, Jr.',
		position: '13',
		source: 'measured-hard'
	},
	B002UZL4ZI: {
		series: 'Hannibal Lecter',
		position: '3',
		source: 'operator-stated'
	},
	B004VA839A: {
		series: 'Hannibal Lecter',
		position: '2',
		source: 'measured-hard'
	},
	B00DZ0G088: {
		series: 'The Riyria Chronicles',
		position: '1',
		source: 'census-verdict'
	},
	B00F5BVQQQ: {
		series: 'The Riyria Chronicles',
		position: '2',
		source: 'census-verdict'
	},
	B0G6MTH7LC: {
		series: 'The Riyria Chronicles',
		position: '2.5',
		source: 'census-verdict'
	},
	B0GDRVSG7Z: {
		series: 'The Riyria Chronicles',
		position: '2.6',
		source: 'census-verdict'
	},
	B0G6MDLP8N: {
		series: 'The Riyria Chronicles',
		position: '3',
		source: 'census-verdict'
	},
	B0D828ZG1Y: {
		series: 'The Riyria Chronicles',
		position: '5',
		source: 'census-verdict'
	},
	B002UZKK2G: {
		series: 'The Original Shannara Trilogy',
		position: '1',
		source: 'measured-hard'
	},
	B018W9PRIU: {
		series: 'The Original Shannara Trilogy',
		position: '2',
		source: 'measured-hard'
	},
	B002VA38KQ: {
		series: 'The Original Shannara Trilogy',
		position: '3',
		source: 'measured-hard'
	},
	B0DFMN335N: {
		series: 'Warhammer 40,000: Imperial Guard',
		position: '1',
		source: 'census-verdict'
	},
	B075QLD2C2: {
		series: 'Eisenhorn',
		position: '1',
		source: 'operator-stated'
	},
	B075QN2PZW: {
		series: 'Eisenhorn',
		position: '2',
		source: 'operator-stated'
	},
	B075QL2BHN: {
		series: 'Eisenhorn',
		position: '3',
		source: 'operator-stated'
	},
	B077PBVD8X: {
		series: 'Eisenhorn',
		position: '0.2',
		source: 'operator-stated'
	},
	B09HKYYT9Q: {
		series: 'The Twice-dead King',
		position: '1',
		source: 'current-correct-default'
	},
	B09PVN67Y6: {
		series: 'The Twice-dead King',
		position: '2',
		source: 'current-correct-default'
	},
	B09WZQQ5XC: {
		series: 'Forges of Mars',
		position: '2',
		source: 'current-correct-default'
	},
	B0763ZZL1W: {
		series: 'The Horus Heresy: Primarchs',
		position: '5',
		source: 'current-correct-default'
	},
	'180026643X': {
		series: 'Dark Imperium',
		position: '2',
		source: 'current-correct-default'
	},
	B077DGBRTY: {
		series: 'Blood Angels',
		position: '3.5',
		source: 'current-correct-default'
	},
	'apple-audiobook-595807561': {
		series: 'The Legend of Drizzt',
		position: '23',
		displayTitle: 'Gauntlgrym',
		source: 'measured-hard'
	},
	'apple-audiobook-1032040112': {
		series: 'The Legend of Drizzt',
		position: '31',
		displayTitle: 'Archmage',
		source: 'measured-hard'
	},
	'apple-audiobook-609834561': {
		series: 'The Legend of Drizzt',
		position: '24',
		displayTitle: 'Neverwinter',
		source: 'measured-hard'
	},
	B09FC52TN9: {
		series: 'The Dresden Files',
		position: '17.1',
		source: 'operator-stated'
	},
	B075SM9TB7: {
		series: 'Space Marine Battles',
		position: '2',
		source: 'operator-stated'
	}
}
