import { describe, expect, test } from 'bun:test'

import {
	AUTHOR_FLOOR,
	CONFIDENCE_FLOOR,
	DURATION_TOLERANCE,
	extractAsinAndClean,
	normalizeTitle,
	scoreCandidate,
	TITLE_FLOOR,
	titleSim
} from '#helpers/providers/matchScorer'
import oracle from '#tests/datasets/providers/scorerOracle.json'

// The oracle fixture is generated by the validated Python benchmark
// (audiobook_match_bench.py). These tests assert the TypeScript port reproduces
// its output exactly, so Gate 0's thresholds and zero-false-positive result carry
// over unchanged. Float comparisons use a tight tolerance to absorb only IEEE
// representation differences between the two runtimes.
const EPS = 1e-9

describe('matchScorer constants match the benchmark', () => {
	test('thresholds are identical to the Python original', () => {
		expect(TITLE_FLOOR).toBe(oracle.constants.TITLE_FLOOR)
		expect(AUTHOR_FLOOR).toBe(oracle.constants.AUTHOR_FLOOR)
		expect(DURATION_TOLERANCE).toBe(oracle.constants.DURATION_TOLERANCE)
		expect(CONFIDENCE_FLOOR).toBeCloseTo(oracle.constants.floor, 12)
	})
})

describe('normalizeTitle matches the Python normalizer', () => {
	for (const c of oracle.normalize) {
		test(`"${c.raw}" -> "${c.expected}"`, () => {
			expect(normalizeTitle(c.raw)).toBe(c.expected)
		})
	}
})

describe('titleSim matches Python difflib-based similarity', () => {
	for (const c of oracle.title_sim) {
		test(`sim("${c.a}", "${c.b}") == ${c.expected}`, () => {
			expect(Math.abs(titleSim(c.a, c.b) - c.expected)).toBeLessThan(EPS)
		})
	}
})

describe('scoreCandidate reproduces Python confidence and duration delta', () => {
	for (const c of oracle.score) {
		test(`${c.want_title} vs ${c.cand_title}`, () => {
			const got = scoreCandidate(
				c.want_title,
				c.want_author,
				c.cand_title,
				c.cand_authors,
				c.want_ms,
				c.cand_audio_seconds
			)
			expect(Math.abs(got.confidence - c.expected_conf)).toBeLessThan(EPS)
			if (c.expected_delta === null) {
				expect(got.durationDeltaPct).toBeNull()
			} else {
				expect(got.durationDeltaPct).not.toBeNull()
				expect(Math.abs((got.durationDeltaPct as number) - c.expected_delta)).toBeLessThan(EPS)
			}
		})
	}
})

describe('extractAsinAndClean (Audiobookshelf / seanap bracket conventions)', () => {
	const cases: Array<[string, string | null, string]> = [
		// [input, expected asin, expected cleaned title]
		["Demons Don't Dream [B0CJRV5S7M]", 'B0CJRV5S7M', "Demons Don't Dream"],
		["[B0CJRV5S7M] Demons Don't Dream", 'B0CJRV5S7M', "Demons Don't Dream"],
		['A Spell for Chameleon [Xanth 1]', null, 'A Spell for Chameleon'],
		['Castle Roogna [Xanth #3]', null, 'Castle Roogna'],
		['Project Hail Mary', null, 'Project Hail Mary'], // no brackets, unchanged
		['Fahrenheit 451', null, 'Fahrenheit 451'] // number in title is not an ASIN
	]
	for (const [input, asin, title] of cases) {
		test(`"${input}" -> asin=${asin}, title="${title}"`, () => {
			const out = extractAsinAndClean(input)
			expect(out.asin).toBe(asin)
			expect(out.title).toBe(title)
		})
	}

	test('does not treat an ordinary capitalized bracket word as an ASIN', () => {
		// "Bookseller" is B + 9 chars but not an all-caps ASIN — must not match.
		expect(extractAsinAndClean('Some Title [Bookseller]').asin).toBeNull()
	})
})

describe('the duration veto behaves as designed', () => {
	// The Wandering Inn Volume 2: right title+author, wrong volume by runtime.
	test('vetoes a >25% runtime mismatch below the acceptance floor', () => {
		const { confidence } = scoreCandidate(
			'The Wandering Inn',
			'pirate aba',
			'The Wandering Inn',
			['pirate aba'],
			219873000,
			173220
		)
		expect(confidence).toBeLessThan(CONFIDENCE_FLOOR)
	})

	test('corroborates a matching runtime above the floor', () => {
		const { confidence } = scoreCandidate(
			'The Stars, Like Dust',
			'Isaac Asimov',
			'The Stars, Like Dust',
			['Isaac Asimov'],
			29598000,
			29598
		)
		expect(confidence).toBeGreaterThanOrEqual(CONFIDENCE_FLOOR)
	})
})
