import { describe, expect, test } from 'bun:test'

import {
	AUTHOR_FLOOR,
	CONFIDENCE_FLOOR,
	DURATION_TOLERANCE,
	normalizeTitle,
	scoreCandidate,
	TITLE_FLOOR,
	titleSim
} from '#helpers/providers/matchScorer'
import oracle from '#tests/datasets/providers/scorerOracle.json'

// The oracle fixture is generated by the validated Python benchmark
// (audiobook_match_bench.py). These tests assert the TypeScript port reproduces
// its output exactly, so Gate 0's thresholds and zero-false-positive result carry
// over unchanged. Float comparisons use a tight tolerance to absorb only IEEE
// representation differences between the two runtimes.
const EPS = 1e-9

describe('matchScorer constants match the benchmark', () => {
	test('thresholds are identical to the Python original', () => {
		expect(TITLE_FLOOR).toBe(oracle.constants.TITLE_FLOOR)
		expect(AUTHOR_FLOOR).toBe(oracle.constants.AUTHOR_FLOOR)
		expect(DURATION_TOLERANCE).toBe(oracle.constants.DURATION_TOLERANCE)
		expect(CONFIDENCE_FLOOR).toBeCloseTo(oracle.constants.floor, 12)
	})
})

describe('normalizeTitle matches the Python normalizer', () => {
	for (const c of oracle.normalize) {
		test(`"${c.raw}" -> "${c.expected}"`, () => {
			expect(normalizeTitle(c.raw)).toBe(c.expected)
		})
	}
})

describe('titleSim matches Python difflib-based similarity', () => {
	for (const c of oracle.title_sim) {
		test(`sim("${c.a}", "${c.b}") == ${c.expected}`, () => {
			expect(Math.abs(titleSim(c.a, c.b) - c.expected)).toBeLessThan(EPS)
		})
	}
})

describe('scoreCandidate reproduces Python confidence and duration delta', () => {
	for (const c of oracle.score) {
		test(`${c.want_title} vs ${c.cand_title}`, () => {
			const got = scoreCandidate(
				c.want_title,
				c.want_author,
				c.cand_title,
				c.cand_authors,
				c.want_ms,
				c.cand_audio_seconds
			)
			expect(Math.abs(got.confidence - c.expected_conf)).toBeLessThan(EPS)
			if (c.expected_delta === null) {
				expect(got.durationDeltaPct).toBeNull()
			} else {
				expect(got.durationDeltaPct).not.toBeNull()
				expect(Math.abs((got.durationDeltaPct as number) - c.expected_delta)).toBeLessThan(EPS)
			}
		})
	}
})

describe('the duration veto behaves as designed', () => {
	// The Wandering Inn Volume 2: right title+author, wrong volume by runtime.
	test('vetoes a >25% runtime mismatch below the acceptance floor', () => {
		const { confidence } = scoreCandidate(
			'The Wandering Inn',
			'pirate aba',
			'The Wandering Inn',
			['pirate aba'],
			219873000,
			173220
		)
		expect(confidence).toBeLessThan(CONFIDENCE_FLOOR)
	})

	test('corroborates a matching runtime above the floor', () => {
		const { confidence } = scoreCandidate(
			'The Stars, Like Dust',
			'Isaac Asimov',
			'The Stars, Like Dust',
			['Isaac Asimov'],
			29598000,
			29598
		)
		expect(confidence).toBeGreaterThanOrEqual(CONFIDENCE_FLOOR)
	})
})
