import { describe, expect, test } from 'bun:test'

import {
	AUTHOR_FLOOR,
	CONFIDENCE_FLOOR,
	DURATION_TOLERANCE,
	extractAsinAndClean,
	normalizeTitle,
	scoreCandidate,
	TITLE_FLOOR,
	titleSim
} from '#helpers/providers/matchScorer'
import oracle from '#tests/datasets/providers/scorerOracle.json'

// The oracle fixture is generated by the validated Python benchmark
// (audiobook_match_bench.py). These tests assert the TypeScript port reproduces
// its output exactly, so Gate 0's thresholds and zero-false-positive result carry
// over unchanged. Float comparisons use a tight tolerance to absorb only IEEE
// representation differences between the two runtimes.
const EPS = 1e-9

describe('matchScorer constants match the benchmark', () => {
	test('thresholds are identical to the Python original', () => {
		expect(TITLE_FLOOR).toBe(oracle.constants.TITLE_FLOOR)
		expect(AUTHOR_FLOOR).toBe(oracle.constants.AUTHOR_FLOOR)
		expect(DURATION_TOLERANCE).toBe(oracle.constants.DURATION_TOLERANCE)
		expect(CONFIDENCE_FLOOR).toBeCloseTo(oracle.constants.floor, 12)
	})
})

describe('normalizeTitle matches the Python normalizer', () => {
	for (const c of oracle.normalize) {
		test(`"${c.raw}" -> "${c.expected}"`, () => {
			expect(normalizeTitle(c.raw)).toBe(c.expected)
		})
	}
})

describe('normalizeTitle strips a glued series-code prefix (DW23 -) safely', () => {
	test('strips a 2-5 letter + digits code followed by a dash', () => {
		expect(normalizeTitle('DW23 - Carpe Jugulum')).toBe('Carpe Jugulum')
		expect(normalizeTitle('GOT1 - A Game of Thrones')).toBe('A Game of Thrones')
		expect(normalizeTitle('HP1 - The Sorcerer Stone')).toBe('The Sorcerer Stone')
	})

	test('leaves real titles untouched', () => {
		// single-letter codes, standalone numbers/acronyms, no-dash, lowercase
		for (const t of [
			'V2 - A Novel',
			'R2 - Something',
			'2001: A Space Odyssey',
			'Fahrenheit 451',
			'Steel World',
			'Mistborn: The Final Empire',
			'1984',
			'dw23 - lowercase code'
		]) {
			expect(normalizeTitle(t)).toBe(t)
		}
	})
})

describe('normalizeTitle keeps date-shaped titles but still strips track prefixes', () => {
	test('a leading number-dash is kept when another number follows (a date)', () => {
		// The leading "NN - " strip must not eat the first field of a date.
		expect(normalizeTitle('11-22-63')).toBe('11-22-63')
		expect(normalizeTitle('9-11')).toBe('9-11')
	})

	test('a leading track number-dash before a real title is still stripped', () => {
		expect(normalizeTitle('01 - Dead I Well May Be')).toBe('Dead I Well May Be')
		expect(normalizeTitle('1. The Gunslinger')).toBe('The Gunslinger')
		expect(normalizeTitle('16 - Loamhedge')).toBe('Loamhedge')
	})
})

describe('normalizeTitle strips a series-first "<Series>, Book N:" prefix', () => {
	test('extracts the real title from a colon or dash series-first tag', () => {
		expect(normalizeTitle('Dresden Files, Book 16: Peace Talks')).toBe('Peace Talks')
		expect(normalizeTitle('Dresden Files, Book 16 - Peace Talks')).toBe('Peace Talks')
		expect(normalizeTitle('Redwall, Book 1: The Wall')).toBe('The Wall')
	})

	test('does not touch a title-first "<Title>: <Series>, Book N" (handled by the suffix)', () => {
		// The suffix rule runs first, so this reduces to the title, not the series.
		expect(normalizeTitle('Task Force Hammer: Expeditionary Force, Book 17')).toBe(
			'Task Force Hammer'
		)
	})
})

describe('titleSim matches Python difflib-based similarity', () => {
	for (const c of oracle.title_sim) {
		test(`sim("${c.a}", "${c.b}") == ${c.expected}`, () => {
			expect(Math.abs(titleSim(c.a, c.b) - c.expected)).toBeLessThan(EPS)
		})
	}
})

describe('scoreCandidate reproduces Python confidence and duration delta', () => {
	for (const c of oracle.score) {
		test(`${c.want_title} vs ${c.cand_title}`, () => {
			const got = scoreCandidate(
				c.want_title,
				c.want_author,
				c.cand_title,
				c.cand_authors,
				c.want_ms,
				c.cand_audio_seconds
			)
			expect(Math.abs(got.confidence - c.expected_conf)).toBeLessThan(EPS)
			if (c.expected_delta === null) {
				expect(got.durationDeltaPct).toBeNull()
			} else {
				expect(got.durationDeltaPct).not.toBeNull()
				expect(Math.abs((got.durationDeltaPct as number) - c.expected_delta)).toBeLessThan(EPS)
			}
		})
	}
})

describe('extractAsinAndClean (Audiobookshelf / seanap bracket conventions)', () => {
	const cases: Array<[string, string | null, string]> = [
		// [input, expected asin, expected cleaned title]
		["Demons Don't Dream [B0CJRV5S7M]", 'B0CJRV5S7M', "Demons Don't Dream"],
		["[B0CJRV5S7M] Demons Don't Dream", 'B0CJRV5S7M', "Demons Don't Dream"],
		['A Spell for Chameleon [Xanth 1]', null, 'A Spell for Chameleon'],
		['Castle Roogna [Xanth #3]', null, 'Castle Roogna'],
		['Project Hail Mary', null, 'Project Hail Mary'], // no brackets, unchanged
		['Fahrenheit 451', null, 'Fahrenheit 451'] // number in title is not an ASIN
	]
	for (const [input, asin, title] of cases) {
		test(`"${input}" -> asin=${asin}, title="${title}"`, () => {
			const out = extractAsinAndClean(input)
			expect(out.asin).toBe(asin)
			expect(out.title).toBe(title)
		})
	}

	test('does not treat an ordinary capitalized bracket word as an ASIN', () => {
		// "Bookseller" is B + 9 chars but not an all-caps ASIN — must not match.
		expect(extractAsinAndClean('Some Title [Bookseller]').asin).toBeNull()
	})
})

describe('the duration veto behaves as designed', () => {
	// The Wandering Inn Volume 2: right title+author, wrong volume by runtime.
	test('vetoes a >25% runtime mismatch below the acceptance floor', () => {
		const { confidence } = scoreCandidate(
			'The Wandering Inn',
			'pirate aba',
			'The Wandering Inn',
			['pirate aba'],
			219873000,
			173220
		)
		expect(confidence).toBeLessThan(CONFIDENCE_FLOOR)
	})

	test('corroborates a matching runtime above the floor', () => {
		const { confidence } = scoreCandidate(
			'The Stars, Like Dust',
			'Isaac Asimov',
			'The Stars, Like Dust',
			['Isaac Asimov'],
			29598000,
			29598
		)
		expect(confidence).toBeGreaterThanOrEqual(CONFIDENCE_FLOOR)
	})
})
