/**
 * Audible's own genre vocabulary, as a fold-key -> spelling table.
 *
 * WHY. Community feeds reach the same genre by a different spelling — "Science
 * fiction" for Audible's "Science Fiction", "Anthology" for "Anthologies".
 * Inside one book the merge already folds those together, but ACROSS the
 * library nothing did, so Plex's genre filter listed both as separate tags.
 * Audible's spelling is the house standard (its entries are never rewritten by
 * the merge), so a community name that folds onto an Audible key adopts it.
 *
 * DERIVED, not hand-written: every key below is dedupeKey() of a genre Audible
 * actually returned for this library, taken from the 1,758 cached books on
 * 2026-08-09 and kept only where two or more books agreed. It is a snapshot of
 * a bounded taxonomy, not a guess — regenerate it the same way if Audible's
 * categories move. Where two Audible spellings share a key the shorter wins.
 */
export const AUDIBLE_VOCABULARY: ReadonlyArray<readonly [string, string]> = [
	['20th century', '20th Century'],
	['action adventure', 'Action & Adventure'],
	['adventure', 'Adventure'],
	['african american', 'African American'],
	['alien', 'Aliens'],
	['alternate history', 'Alternate History'],
	['amateur sleuth', 'Amateur Sleuths'],
	['ancient classical medieval literature', 'Ancient, Classical & Medieval Literature'],
	['ancient world', 'Ancient World'],
	['ancient', 'Ancient'],
	['animal fiction', 'Animal Fiction'],
	['animal', 'Animals'],
	['animals nature', 'Animals & Nature'],
	['anthologies short story', 'Anthologies & Short Stories'],
	['anthology', 'Anthologies'],
	['arts entertainment', 'Arts & Entertainment'],
	['baseball softball', 'Baseball & Softball'],
	['biographical fiction', 'Biographical Fiction'],
	['biographies memoir', 'Biographies & Memoirs'],
	['books library', 'Books & Libraries'],
	['business career', 'Business & Careers'],
	['business development entrepreneurship', 'Business Development & Entrepreneurship'],
	['career succes', 'Career Success'],
	['childrens audiobook', "Children's Audiobooks"],
	['christian fiction', 'Christian Fiction'],
	['classic', 'Classics'],
	['collection', 'Collections'],
	['comedy humor', 'Comedy & Humor'],
	['coming of age', 'Coming of Age'],
	['communication social skill', 'Communication & Social Skills'],
	['contemporary fiction', 'Contemporary Fiction'],
	['contemporary', 'Contemporary'],
	['cozy', 'Cozy'],
	['crime fiction', 'Crime Fiction'],
	['crime thriller', 'Crime Thrillers'],
	['crime', 'Crime'],
	['cult', 'Cults'],
	['cyberpunk', 'Cyberpunk'],
	['death dying', 'Death & Dying'],
	['death grief los', 'Death, Grief & Loss'],
	['difficult discussion', 'Difficult Discussions'],
	['difficult situation', 'Difficult Situations'],
	['domestic thriller', 'Domestic Thrillers'],
	['dragons mythical creatur', 'Dragons & Mythical Creatures'],
	['drama play', 'Drama & Plays'],
	['dramatization', 'Dramatizations'],
	['dystopian', 'Dystopian'],
	['education learning', 'Education & Learning'],
	['education', 'Education'],
	['epic', 'Epic'],
	['espionage', 'Espionage'],
	['essay', 'Essays'],
	['ethics morality', 'Ethics & Morality'],
	['europe', 'Europe'],
	['explore the world', 'Explore the World'],
	['fairy tal', 'Fairy Tales'],
	['fairy tales folk tales myth', 'Fairy Tales, Folk Tales & Myths'],
	['family life', 'Family Life'],
	['family relationship', 'Family & Relationships'],
	['family', 'Family'],
	['fantasy magic', 'Fantasy & Magic'],
	['fantasy', 'Fantasy'],
	['first contact', 'First Contact'],
	['friendship', 'Friendship'],
	['gaslamp', 'Gaslamp'],
	['genetic engineering', 'Genetic Engineering'],
	['genre fiction', 'Genre Fiction'],
	['geography cultur', 'Geography & Cultures'],
	['ghost', 'Ghosts'],
	['greece', 'Greece'],
	['greek roman', 'Greek & Roman'],
	['growing up facts of life', 'Growing Up & Facts of Life'],
	['hard science fiction', 'Hard Science Fiction'],
	['hardboiled', 'Hard-Boiled'],
	['health wellnes', 'Health & Wellness'],
	['historical fiction', 'Historical Fiction'],
	['historical', 'Historical'],
	['history', 'History'],
	['holiday', 'Holidays'],
	['horror', 'Horror'],
	['humor', 'Humor'],
	['humorou', 'Humorous'],
	['humorous fiction', 'Humorous Fiction'],
	['international mystery crime', 'International Mystery & Crime'],
	['legal', 'Legal'],
	['literary fiction', 'Literary Fiction'],
	['literary history criticism', 'Literary History & Criticism'],
	['literature fiction', 'Literature & Fiction'],
	['magical realism', 'Magical Realism'],
	['management leadership', 'Management & Leadership'],
	['marketing sal', 'Marketing & Sales'],
	['marketing', 'Marketing'],
	['medical', 'Medical'],
	['metaphysical visionary', 'Metaphysical & Visionary'],
	['mice hamsters guinea pigs squirrel', 'Mice, Hamsters, Guinea Pigs & Squirrels'],
	['military', 'Military'],
	['money finance', 'Money & Finance'],
	['motivation selfimprovement', 'Motivation & Self-Improvement'],
	['movie tv video game tiein', 'Movie, TV & Video Game Tie-Ins'],
	['mysteries detectiv', 'Mysteries & Detectives'],
	['mystery suspense', 'Mystery & Suspense'],
	['mystery thriller suspense', 'Mystery, Thriller & Suspense'],
	['mystery', 'Mystery'],
	['noir', 'Noir'],
	['occult', 'Occult'],
	['paranormal urban', 'Paranormal & Urban'],
	['paranormal', 'Paranormal'],
	['personal development', 'Personal Development'],
	['personal succes', 'Personal Success'],
	['philosophy', 'Philosophy'],
	['poetry', 'Poetry'],
	['police procedural', 'Police Procedurals'],
	['political science', 'Political Science'],
	['political', 'Political'],
	['politics government', 'Politics & Government'],
	['politics social scienc', 'Politics & Social Sciences'],
	['popular culture', 'Popular Culture'],
	['postapocalyptic', 'Post-Apocalyptic'],
	['private investigator', 'Private Investigators'],
	['psychological', 'Psychological'],
	['psychology mental health', 'Psychology & Mental Health'],
	['psychology', 'Psychology'],
	['relationship', 'Relationships'],
	[
		'relationships parenting personal development',
		'Relationships, Parenting & Personal Development'
	],
	['religion spirituality', 'Religion & Spirituality'],
	['religious fiction', 'Religious Fiction'],
	['religious study', 'Religious Studies'],
	['romance', 'Romance'],
	['saga', 'Sagas'],
	['satire', 'Satire'],
	['scary story', 'Scary Stories'],
	['science fiction fantasy', 'Science Fiction & Fantasy'],
	['science fiction', 'Science Fiction'],
	['sea adventur', 'Sea Adventures'],
	['serial killer', 'Serial Killers'],
	['short story', 'Short Stories'],
	['small town rural', 'Small Town & Rural'],
	['social life skill', 'Social & Life Skills'],
	['social scienc', 'Social Sciences'],
	['space exploration', 'Space Exploration'],
	['space opera', 'Space Opera'],
	['spies politic', 'Spies & Politics'],
	['sport', 'Sports'],
	['sports outdoor', 'Sports & Outdoors'],
	['steampunk', 'Steampunk'],
	['superhero', 'Superhero'],
	['supernatural', 'Supernatural'],
	['suspense', 'Suspense'],
	['sword sorcery', 'Sword & Sorcery'],
	['technothriller', 'Technothrillers'],
	['teen young adult', 'Teen & Young Adult'],
	['terrorism', 'Terrorism'],
	['themes styl', 'Themes & Styles'],
	['thriller suspense', 'Thriller & Suspense'],
	['thrillers suspense', 'Thrillers & Suspense'],
	['time travel', 'Time Travel'],
	['traditional detectiv', 'Traditional Detectives'],
	['united stat', 'United States'],
	['urban', 'Urban'],
	['war military', 'War & Military'],
	['wars conflict', 'Wars & Conflicts'],
	['weapons warfare', 'Weapons & Warfare'],
	['western', 'Westerns'],
	['women sleuth', 'Women Sleuths'],
	['women', 'Women'],
	['womens fiction', "Women's Fiction"],
	['words language grammar', 'Words, Language & Grammar'],
	['world literature', 'World Literature'],
	['writing publishing', 'Writing & Publishing']
]
