/**
 * Book-match normalizer and scorer, ported from the validated Gate 0 benchmark
 * (`audiobook_match_bench.py`). Behaviour is asserted bit-for-bit against a
 * fixture generated by the Python original — see tests/helpers/providers.
 *
 * Two responsibilities:
 *  - normalizeTitle: strip audiobook-rip noise from a Plex ALBUM tag.
 *  - scoreCandidate: rank a provider candidate against what Plex wants, using
 *    title + author similarity and (when both sides have it) a DURATION signal
 *    that corroborates a right edition or vetoes a wrong one.
 */

import { ratcliffObershelp } from '#helpers/utils/stringSimilarity'

// Thresholds — validated in the bench; do not retune without re-running Gate 0.
export const TITLE_FLOOR = 0.8
export const AUTHOR_FLOOR = 0.7
export const DURATION_TOLERANCE = 0.05 // +/-5% counts as a duration corroboration
// Acceptance floor: a perfect-ish title+author with no duration signal.
export const CONFIDENCE_FLOOR = TITLE_FLOOR * 0.55 + AUTHOR_FLOOR * 0.3

// Audiobook rips carry a lot of noise in the ALBUM tag. Strip it before matching.
const NOISE_PATTERNS: RegExp[] = [
	/\((un)?abridged\)/gi,
	/\[(un)?abridged\]/gi,
	/\bunabridged\b/gi,
	/\baudiobook\b/gi,
	/\bbook\s+\d+\b/gi,
	/\bvol(ume)?\.?\s*\d+\b/gi,
	/\bpart\s+\d+\b/gi,
	/\bdisc\s+\d+\b/gi,
	/^\s*\d{1,3}\s*[-._]\s*/gi, // leading "01 - "
	/^\s*\[\d{1,3}\]\s*/gi, // leading "[01] "
	// Leading zero-padded track number with only a space: "01 The Stars, Like Dust".
	// The zero pad guard keeps real titles starting with a number ("1984") intact.
	/^\s*0\d{0,2}\s+/gi,
	// Bracketed series prefix carrying a name: "[The Expanse 0.5] ", "[Victor 13] - ".
	/^\s*\[[^\]]{1,40}\]\s*[-–—]?\s*/gi
]

// Leading "<Series> 01 - " / "<Series> #3 - ". Requires a dash separator so it
// can't eat titles like "Fahrenheit 451".
const SERIES_PREFIX: RegExp[] = [
	/^\s*[A-Za-z'’. ]{2,25}\s+#?\d{1,3}\s*[-–—]\s+/,
	// "<Series>, Book N - <Title>": must run before the generic \bbook \d+\b noise
	// rule, which would otherwise strand a dangling ", - " in the middle.
	/^\s*[^,]{2,30},\s*book\s+\d+\s*[-–—]\s+/i
]

// Trailing series suffix: ": Xanth, Book 16" / " (Xanth #3)" / ", Book 2".
// The colon/dash form runs first and may span an internal comma, or the plain
// comma rule fires early and strands the ": Xanth" fragment.
const SERIES_SUFFIX: RegExp[] = [
	/\s*[:\-–—]\s*[^:]*?\bbook\s+\d+\s*$/i,
	/\s*\([^)]*#\s*\d+\s*\)\s*$/,
	/\s*,\s*book\s+\d+\s*$/i
]

/**
 * Strip audiobook-rip noise from an ALBUM tag.
 * Order matters: series suffixes must go BEFORE generic noise stripping, or
 * "Book 16" is removed first and the ": Xanth," fragment survives.
 * @param {string} raw the raw ALBUM tag
 * @returns {string} the cleaned title
 */
export function normalizeTitle(raw: string | null | undefined): string {
	if (!raw) return ''
	let t = raw.trim()

	// 1. series suffix first (needs the "Book N" text still present)
	for (const pat of SERIES_SUFFIX) t = t.replace(pat, '')
	// 2. series prefix
	for (const pat of SERIES_PREFIX) t = t.replace(pat, '')
	// 3. generic noise
	for (const pat of NOISE_PATTERNS) t = t.replace(pat, ' ')

	t = t.replace(/[_.]+/g, ' ')
	t = t.replace(/\s{2,}/g, ' ')
	return t.replace(/^[\s\-–—:,]+|[\s\-–—:,]+$/g, '')
}

// Audible ASIN shape: 10 chars beginning with B, e.g. B0CJRV5S7M. Deliberately
// narrow so it does not catch ISBN digits or arbitrary bracket contents.
const ASIN_RE = /\bB[0-9A-Z]{9}\b/
// A leading or trailing bracketed token, e.g. "[Xanth 1]" or "[B0CJRV5S7M]".
const EDGE_BRACKET = /^\s*\[[^\]]{1,40}\]\s*|\s*\[[^\]]{1,40}\]\s*$/g

/**
 * Pull an ASIN out of a raw ALBUM tag and strip edge bracket tokens, before
 * normalization.
 *
 * Audiobookshelf and the seanap Plex convention both embed the Audible ASIN in
 * brackets ("Demons Don't Dream [B0CJRV5S7M]") and put series info in trailing
 * brackets ("A Spell for Chameleon [Xanth 1]"). Those brackets destroy provider
 * recall — a bracketed title returns zero results from Audible's catalog search —
 * and the ASIN is the single most reliable match key, so both are worth
 * recovering here rather than leaving in the query.
 * @param {string} raw the raw ALBUM tag
 * @returns {{ asin: string | null; title: string }} extracted ASIN and de-bracketed title
 */
export function extractAsinAndClean(raw: string | null | undefined): {
	asin: string | null
	title: string
} {
	if (!raw) return { asin: null, title: '' }
	let asin: string | null = null
	// Scan bracketed tokens for an ASIN.
	const bracketed = /[[(]([^\])]{1,40})[\])]/g
	let m: RegExpExecArray | null
	while ((m = bracketed.exec(raw)) !== null) {
		const found = m[1].match(ASIN_RE)
		if (found) {
			asin = found[0].toUpperCase()
			break
		}
	}
	const title = raw
		.replace(EDGE_BRACKET, ' ')
		.replace(/\s{2,}/g, ' ')
		.trim()
	return { asin, title }
}

/**
 * 0.0-1.0 similarity, case/punctuation insensitive. Mirrors the bench `sim()`.
 * @param {string} a first string
 * @param {string} b second string
 */
export function sim(a: string, b: string): number {
	if (!a || !b) return 0.0
	const clean = (s: string) =>
		s
			.toLowerCase()
			.replace(/[^a-z0-9 ]/g, '')
			.trim()
	return ratcliffObershelp(clean(a), clean(b))
}

/** Text before the first subtitle separator (":" or "("). */
function baseTitle(s: string): string {
	if (!s) return ''
	return s.split(/\s*[:(]\s*/)[0].trim()
}

/**
 * Subtitle-tolerant title similarity. Providers routinely carry a subtitle the
 * ALBUM tag omits ("Esrever Doom: A Fun-Filled Adventure..."), which a raw ratio
 * scores far too low. Compare the pre-subtitle stems too and take the best.
 * @param {string} want the Plex-side title
 * @param {string} cand the candidate title
 */
export function titleSim(want: string, cand: string): number {
	if (!want || !cand) return 0.0
	return Math.max(
		sim(want, cand),
		sim(baseTitle(want), baseTitle(cand)),
		sim(baseTitle(want), cand),
		sim(want, baseTitle(cand))
	)
}

export interface CandidateScore {
	confidence: number
	durationDeltaPct: number | null
}

/**
 * Score a provider candidate against what Plex wants.
 * @param {string} wantTitle normalized Plex title
 * @param {string} wantAuthor Plex author
 * @param {string} candTitle candidate title
 * @param {string[]} candAuthors candidate authors
 * @param {number|null} wantMs Plex album duration in ms (summed tracks)
 * @param {number|null} candAudioSeconds candidate audio edition length in seconds
 * @returns {CandidateScore} confidence in [0,1] and the duration delta fraction
 */
export function scoreCandidate(
	wantTitle: string,
	wantAuthor: string,
	candTitle: string,
	candAuthors: string[],
	wantMs: number | null = null,
	candAudioSeconds: number | null = null
): CandidateScore {
	const t = titleSim(wantTitle, candTitle)
	const authorScores = candAuthors.map((x) => sim(wantAuthor, x))
	const a = authorScores.length ? Math.max(...authorScores) : 0.0

	let durDelta: number | null = null
	let durBonus = 0.0
	if (wantMs && candAudioSeconds) {
		const wantS = wantMs / 1000.0
		durDelta = Math.abs(wantS - candAudioSeconds) / candAudioSeconds
		if (durDelta <= DURATION_TOLERANCE)
			durBonus = 0.15 // corroborates
		else if (durDelta > 0.25) durBonus = -0.3 // actively contradicts — wrong edition
	}

	// With an author, weight title 0.55 + author 0.30 (the validated model). Album
	// searches often arrive with no author (Plex passes the album but not the
	// artist name), so score on title alone rather than let the missing author cap
	// confidence below the floor.
	const conf = wantAuthor ? 0.55 * t + 0.3 * a + durBonus : t + durBonus
	return {
		confidence: Math.max(0.0, Math.min(1.0, conf)),
		durationDeltaPct: durDelta
	}
}
