/**
 * Mint shelf pins from the golden corpus + the current harness baseline.
 *
 * A pin is minted ONLY for a record that is (a) a standing red in the
 * baseline and (b) carries a corpus REQUIRED outcome of SERIES — i.e. the
 * operator has already stated the answer. Conditional/pending rows are never
 * minted. Output overwrites src/helpers/series/shelfPins.data.ts.
 */
import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

const FIXTURES = join(import.meta.dir, '..', 'tests', 'fixtures')
interface Row {
	recordId: string
	ratingKey: string
	album: string
	pinType: string
	required: {
		outcome: string
		series?: string | null
		position?: string | null
		displayTitle?: string | null
	}
	mintPin?: boolean
}
const corpus = JSON.parse(readFileSync(join(FIXTURES, 'series-golden-corpus.json'), 'utf8')) as {
	rows: Row[]
}
// Pins are DURABLE, flag-driven corpus policy: minted from rows the operator
// has marked mintPin, never from the baseline — a pin heals its red, so a
// baseline-derived generator erases its own inputs on the next run (caught
// live: regenerating after the pins landed dropped all 32).
const red = new Set(corpus.rows.filter((r) => r.mintPin).map((r) => r.ratingKey))
const byRk = new Map(corpus.rows.map((r) => [r.ratingKey, r]))
const pins: Record<string, { series: string; position?: string; source: string }> = {}
const skipped: string[] = []
for (const rk of red) {
	const row = byRk.get(rk)
	if (!row) continue
	if (row.required.outcome !== 'SERIES' || !row.required.series) {
		skipped.push(`rk${rk} ${row.album} (${row.required.outcome})`)
		continue
	}
	pins[row.recordId] = {
		series: row.required.series,
		...(row.required.position ? { position: row.required.position } : {}),
		...(row.required.displayTitle ? { displayTitle: row.required.displayTitle } : {}),
		source: row.pinType
	}
}
const body = `/**
 * GENERATED by scripts/mintPins.ts from tests/fixtures/series-golden-corpus.json
 * + series-harness-baseline.json — do not hand-edit; edit the corpus and
 * regenerate. Minted ${Object.keys(pins).length} pins.
 */
import type { ShelfPin } from './shelfPins'

export const SHELF_PINS: Record<string, ShelfPin> = ${JSON.stringify(pins, null, '\t')}
`
writeFileSync(join(import.meta.dir, '..', 'src', 'helpers', 'series', 'shelfPins.data.ts'), body)
console.log(`minted ${Object.keys(pins).length} pins`)
for (const s of skipped) console.log(`  skipped (not SERIES-required): ${s}`)
