/**
 * Mint shelf pins from the golden corpus + the current harness baseline.
 *
 * A pin is minted ONLY for a record that is (a) a standing red in the
 * baseline and (b) carries a corpus REQUIRED outcome of SERIES — i.e. the
 * operator has already stated the answer. Conditional/pending rows are never
 * minted. Output overwrites src/helpers/series/shelfPins.data.ts.
 */
import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

import { pinKey, pinKeyAliases } from '#helpers/series/pinKey'

const FIXTURES = join(import.meta.dir, '..', 'tests', 'fixtures')
interface Row {
	recordId: string
	ratingKey: string
	album: string
	artist?: string
	pinType: string
	inputs?: {
		title?: string | null
		author?: string | null
	}
	required: {
		outcome: string
		series?: string | null
		position?: string | null
		displayTitle?: string | null
	}
	mintPin?: boolean
}
const corpus = JSON.parse(readFileSync(join(FIXTURES, 'series-golden-corpus.json'), 'utf8')) as {
	rows: Row[]
}
// Pins are DURABLE, flag-driven corpus policy: minted from rows the operator
// has marked mintPin, never from the baseline — a pin heals its red, so a
// baseline-derived generator erases its own inputs on the next run (caught
// live: regenerating after the pins landed dropped all 32).
const red = new Set(corpus.rows.filter((r) => r.mintPin).map((r) => r.ratingKey))
const byRk = new Map(corpus.rows.map((r) => [r.ratingKey, r]))
type Minted = { series: string; position?: string; displayTitle?: string; source: string }
const pins: Record<string, Minted> = {}
/** The same pins, keyed on the portable (title, author) identity. */
const keyed: Record<string, Minted> = {}
const keyOwner: Record<string, string> = {}
/** recordId -> EVERY key it is filed under, so the liveness gate can join the
 *  tables exactly instead of guessing from the answer they carry. Plural
 *  because a pin may also carry a baked-in-series alias; storing only the
 *  primary reported five alias-reachable pins dead on prod. */
const keyByRecord: Record<string, string[]> = {}
const skipped: string[] = []
const missing: string[] = []
const collisions: string[] = []
const keyCollisions: string[] = []
const unkeyable: string[] = []
for (const rk of red) {
	const row = byRk.get(rk)
	if (!row) {
		missing.push(`rk${rk}`)
		continue
	}
	if (row.required.outcome !== 'SERIES' || !row.required.series) {
		skipped.push(`rk${rk} ${row.album} (${row.required.outcome})`)
		continue
	}
	// A recordId already minted means two corpus rows claim the same record with
	// (potentially) different answers, and the later one silently won. The corpus
	// carries 5 duplicate recordIds across 4 groups today; none is currently
	// flagged mintPin, which is the only reason this has not already bitten.
	if (pins[row.recordId]) {
		collisions.push(
			`${row.recordId} (rk${rk} ${row.album}) already minted as ` +
				`${pins[row.recordId].series} #${pins[row.recordId].position ?? '-'}`
		)
		continue
	}
	pins[row.recordId] = {
		series: row.required.series,
		...(row.required.position ? { position: row.required.position } : {}),
		...(row.required.displayTitle ? { displayTitle: row.required.displayTitle } : {}),
		source: row.pinType
	}
	// The portable key, minted from the PRE-pin provider strings. inputs.title
	// deliberately, never the album name or required.displayTitle: applyPins
	// looks the pin up BEFORE it rewrites the title, so keying on the rewritten
	// one would be circular and would never match.
	const k = pinKey(row.inputs?.title ?? row.album, row.inputs?.author)
	if (!k) {
		unkeyable.push(
			`${row.recordId} rk${rk} ${row.album} (author: ${JSON.stringify(row.inputs?.author)})`
		)
		continue
	}
	const prior = keyed[k]
	if (prior && JSON.stringify(prior) !== JSON.stringify(pins[row.recordId])) {
		keyCollisions.push(
			`"${k}" claimed by rk${rk} ${row.album} (${pins[row.recordId].series} #${pins[row.recordId].position ?? '-'}) ` +
				`and already by ${prior.series} #${prior.position ?? '-'}`
		)
		continue
	}
	keyed[k] = pins[row.recordId]
	keyByRecord[row.recordId] = [k]
	keyOwner[k] = `rk${rk} ${row.album}`
	// ...plus the plain-title form, when this record bakes its own series into
	// the title and another library matched the same book to an edition that
	// does not. Same collision gate: an alias that would claim another pin's key
	// fails the mint rather than silently overwriting it.
	for (const alias of pinKeyAliases(
		row.inputs?.title ?? row.album,
		row.inputs?.author,
		row.required.series
	)) {
		const held = keyed[alias]
		if (held && JSON.stringify(held) !== JSON.stringify(pins[row.recordId])) {
			keyCollisions.push(
				`"${alias}" (alias of rk${rk} ${row.album}) already held by ${keyOwner[alias]}`
			)
			continue
		}
		keyed[alias] = pins[row.recordId]
		keyByRecord[row.recordId] = [...(keyByRecord[row.recordId] ?? []), alias]
		keyOwner[alias] = `rk${rk} ${row.album} (alias)`
	}
}
const body = `/**
 * GENERATED by scripts/mintPins.ts from tests/fixtures/series-golden-corpus.json
 * + series-harness-baseline.json — do not hand-edit; edit the corpus and
 * regenerate. Minted ${Object.keys(pins).length} pins, ${Object.keys(keyByRecord).length} of them portable,
 * under ${Object.keys(keyed).length} keys (some pins carry a baked-in-series alias).
 */
import type { ShelfPin } from './shelfPins'

/** By matched EDITION id — exact, and the only table before 2026-08-11. */
export const SHELF_PINS: Record<string, ShelfPin> = ${JSON.stringify(pins, null, '\t')}

/**
 * The same pins by folded (title, author) — see pinKey. This is what lets one
 * table serve a library that matched the same book to a different edition; the
 * edition-id table above reaches 49 of 90 pins on the second server.
 */
export const SHELF_PINS_BY_KEY: Record<string, ShelfPin> = ${JSON.stringify(keyed, null, '\t')}

/**
 * recordId -> EVERY portable key minted for it. Only the liveness gate needs this:
 * it is how "this pin is dead by id but alive by key" is decided EXACTLY rather
 * than by matching on the answer two different pins could share.
 */
export const SHELF_PIN_KEYS: Record<string, string[]> = ${JSON.stringify(keyByRecord, null, '\t')}
`
const outPath = join(import.meta.dir, '..', 'src', 'helpers', 'series', 'shelfPins.data.ts')
writeFileSync(outPath, body)
// Format the emitted file with the repo's own prettier config. JSON.stringify
// output is not prettier-clean (quoted keys, no trailing commas), and `bun run
// test` does not run the linter -- so a mint that passed every local gate
// failed CI on prettier --check (78ba120, 2026-08-18). Formatting here makes
// the generator's output identical to what a hand edit would have to be.
Bun.spawnSync(
	['bunx', 'prettier', '--config', join(import.meta.dir, '..', '.prettierrc'), '--write', outPath],
	{
		stdout: 'ignore',
		stderr: 'inherit'
	}
)
console.log(`minted ${Object.keys(pins).length} pins`)

// A row the operator flagged mintPin that produced NO pin is a silent hole in
// the operator's own stated answers — exactly what pins exist to prevent. It
// used to print and exit 0, so a green run could ship with the pin missing.
let failed = false
for (const s of skipped) {
	console.error(`  SKIPPED (mintPin row is not SERIES-required): ${s}`)
	failed = true
}
for (const s of missing) {
	console.error(`  MISSING (mintPin ratingKey not in the corpus): ${s}`)
	failed = true
}
for (const s of collisions) {
	console.error(`  COLLISION (two corpus rows claim one recordId): ${s}`)
	failed = true
}
// Two DIFFERENT answers under one portable key: whichever row minted last would
// silently win, and the pin would apply to a book it was never stated for. The
// edition-id table never had this failure mode because an edition id names one
// record; a (title, author) key does not.
for (const s of keyCollisions) {
	console.error(`  KEY COLLISION (two pins claim one title+author): ${s}`)
	failed = true
}
// A pin with no portable key still ships id-keyed, so it is not fatal — but it
// is dead on every other library, which is the whole problem being fixed here.
for (const s of unkeyable) console.warn(`  NOT PORTABLE (no author to key on): ${s}`)
// Count RECORDS, not keys: a pin can be filed under an alias as well as its
// own key, so keyed.length overcounts and would read as >100% portable.
console.log(
	`  ${Object.keys(keyByRecord).length} of ${Object.keys(pins).length} pins are portable ` +
		`(${Object.keys(keyed).length} keys, including aliases)`
)
if (failed) {
	console.error('\nmintPins: refusing to report success — fix the corpus rows above and re-run.')
	process.exit(1)
}
